let pokeneas = [
    {
        'id': 1,
        'nombre': 'hector',
        'altura': 1.5,
        'habilidad': 'lavoe',
        'imagen': 'una',
        'frase':'una cualquiera por ahora',
    },
    {
        'id': 2,
        'nombre': 'Eddie',
        'altura': 1.2,
        'habilidad': 'Santiago',
        'imagen': 'una',
        'frase':'una cualquiera por ahora',
    },
    {
        'id': 3,
        'nombre': 'Gilberto',
        'altura': 1,
        'habilidad': 'Santarosa',
        'imagen': 'una',
        'frase':'una cualquiera por ahora',
    },
    {
        'id': 4,
        'nombre': 'Adolescente',
        'altura': 2.0,
        'habilidad': 'Orquesta',
        'imagen': 'una',
        'frase':'una cualquiera por ahora',
    },
    {
        'id': 5,
        'nombre': 'Juan',
        'altura': 2.1,
        'habilidad': 'Guerra',
        'imagen': 'una',
        'frase':'una cualquiera por ahora',
    },
    {
        'id': 6,
        'nombre': 'Natalia',
        'altura': 0.8,
        'habilidad': 'Laforcade',
        'imagen': 'una',
        'frase':'una cualquiera por ahora',
    },
    {
        'id': 7,
        'nombre': 'Yo',
        'altura': 4,
        'habilidad': 'Soy',
        'imagen': 'una',
        'frase':'una cualquiera por ahora',
    },
];

module.exports = { pokeneas };